// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeqzaatunpiijrcumhse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplcXphYXR1bnBpaWpyY3VtaHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MDk5MTYsImV4cCI6MjA1Mjk4NTkxNn0.XPYg9FhzJJ0REKLsVd5EJFuT87kqHGC3f1PaPt4TtmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);